### ISSUE TITLE
Could not get workflow log

### ISSUE THREAD

**Issue by RihabAlrefae** [nathanwoulfe/Plumber#136]
**Describe the bug**
After installing the workflow 1.1.13 from the NuGet it shows the following error 
![workflow error](https://user-images.githubusercontent.com/51046637/87299352-8505f780-c514-11ea-9659-00707b09fc85.PNG)

and the Log file error is 
 ```
ERROR Workflow.Api.SettingsController - Error getting version information 
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Workflow.Api.SettingsController.GetVersion()
```

Plumber version
1.1.13
Umbraco Version 
7.15.5

**Comment by nathanwoulfe** [comment]
@RihabAlrefae that error is unrelated to the logs exception (changes to GitHub API that I wasn't aware of). Could you please check the UmbracoTraceLog for anything raised by Workflow.Api.LogsController.GetDates()
