### ISSUE TITLE
Approval as admin

### ISSUE THREAD

**Issue by tkf144** [nathanwoulfe/Plumber#140]
Hi Nathan,

This could just be a user/config error so please treat as support rather than a suggestion of defective behaviour.

**Describe the bug**
Non-admin users appear to approve 'as admin' at multiple approval stages in v1.1.10 of Plumber. There are numerous instances of this over the last few months.

Have compared v1.1.10 and v1.1.15 to see if there were any fixes released along these lines but didn't spot anything obvious. Will update to the latest if it's confirmed this isn't just my misunderstanding of how administrators relate to these approvals.

```
SELECT u.userName, count(u.username) as ActionedByAdminCount
FROM [UMBRACO].[dbo].[WorkflowTaskInstance] as t
inner join [dbo].[umbracoUser] u on t.ActionedByUserId = u.id
inner join [dbo].[umbracoUser2UserGroup] as ug on ug.userId = u.id
inner join [dbo].umbracoUserGroup as g on ug.userGroupId = g.id
WHERE t.ActionedByAdmin = 1 AND g.userGroupName != 'Administrators'
group by u.username order by ActionedByAdminCount desc
```
![image](https://user-images.githubusercontent.com/17581159/92713836-cbee5d00-f39e-11ea-8328-67a81173da36.png)

**To Reproduce**
Unsure how this occurs. I'm not well versed in Umbraco or Workflow but have spent the last few hours trying to figure this out.

**Expected behavior**
Non-admin users do not approve 'as admin'

**Screenshots**
You can see the blue user legitimately approved at stage 2, however immediately after they went on to approve 'as admin' all the way through. The blue user is not a member of Umbraco administrators, nor the Workflow groups assigned to the stages beyond stage 2.

![image](https://user-images.githubusercontent.com/17581159/92710399-1b328e80-f39b-11ea-96ac-66a5bd5e8979.png)
![image](https://user-images.githubusercontent.com/17581159/92711521-f4288c80-f39b-11ea-9736-5ca4b5edd6cc.png)
Logs for the above node (details snipped):
```
2020-09-10 14:37:19,173 [164] INFO  Workflow.Api.ActionsController - Workflow Publish task on CONTENT TITLE [6610] approved by NONADMIN USER 
2020-09-10 15:06:03,426 [13] INFO  Workflow.Api.ActionsController - Workflow Publish task on CONTENT TITLE [6610] approved by BLUE USER 
2020-09-10 15:06:09,643 [37] INFO  Workflow.Api.ActionsController - Workflow Publish task on CONTENT TITLE [6610] approved by BLUE USER 
2020-09-10 15:06:12,788 [34] INFO  Workflow.Api.ActionsController - Workflow Publish task on CONTENT TITLE [6610] approved by BLUE USER 
2020-09-10 15:20:36,678 [20] INFO  Workflow.Api.ActionsController - Workflow approved by ADMIN USER on CONTENT TITLE [6610] 
2020-09-10 15:44:42,751 [63] INFO  Workflow.Api.ActionsController - Workflow Publish task on CONTENT TITLE [6610] approved by NONADMIN USER 
2020-09-10 15:45:38,506 [38] INFO  Workflow.Api.ActionsController - Workflow Publish task on CONTENT TITLE [6610] approved by NONADMIN USER 
2020-09-10 15:51:27,025 [65] INFO  Workflow.Api.ActionsController - Publish request for CONTENT TITLE [6610] was cancelled by ADMIN USER 
2020-09-10 15:58:53,038 [22] INFO  Workflow.Api.ActionsController - Workflow Publish task on CONTENT TITLE [6610] approved by BLUE USER 
2020-09-10 15:58:56,968 [149] INFO  Workflow.Api.ActionsController - Workflow Publish task on CONTENT TITLE [6610] approved by BLUE USER 
2020-09-10 15:59:09,448 [125] INFO  Workflow.Api.ActionsController - Workflow Publish task on CONTENT TITLE [6610] approved by BLUE USER 
2020-09-10 15:59:15,813 [67] ERROR Workflow.Api.ActionsController - An error occurred processing the approval on CONTENT TITLE [6610] 
System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at Workflow.Processes.WorkflowProcess.ProcessApprovalAction(WorkflowAction action, Int32 userId, String comment)
   at Workflow.Processes.WorkflowProcess.ActionWorkflow(WorkflowInstancePoco instance, WorkflowAction action, Int32 userId, String comment)
   at Workflow.Api.ActionsController.ApproveWorkflowTask(TaskData model)
2020-09-10 15:59:18,898 [156] INFO  Workflow.Api.ActionsController - Workflow approved by BLUE USER on CONTENT TITLE [6610] 
2020-09-10 15:59:19,010 [122] ERROR Workflow.Api.ActionsController - An error occurred processing the approval on CONTENT TITLE [6610] 
Workflow.Helpers.WorkflowException: Workflow instance 1174 is not pending any action.
   at Workflow.Processes.WorkflowProcess.ActionWorkflow(WorkflowInstancePoco instance, WorkflowAction action, Int32 userId, String comment)
   at Workflow.Api.ActionsController.ApproveWorkflowTask(TaskData model)
```

**Desktop (please complete the following information):**
Can retrieve if you think this would be relevant.

**Plumber version**
Plumber v1.1.10, Umbraco v7.12.1

**Comment by nathanwoulfe** [comment]
Hi @tkf144 

Couple of questions/clarifications - is blue user approving each step, or is the workflow completing automatically (logs look like blue user is approving, just want to confirm); and does blue user have access to the workflow section in the backoffice?

If both of those are true, then this is expected behaviour - for workflow, an admin is anyone with access to the workflow section, whom can then approve any changes regardless of group membership. Workflow permissions are a separate model from the general Umbraco permissions (ie a non-admin Umbraco user can still be a workflow admin). 

I'm hoping this is the case... Let me know  😁

**Comment by tkf144** [comment]
Thanks for the speedy response @nathanwoulfe.

> for workflow, an admin is anyone with access to the workflow section, whom can then approve any changes regardless of group membership.

Great - that's useful clarification. Thank you. Members of the 'Administrators' group are the only users with access to the Workflow section, so am I right to interpret here that as: Umbraco 'Administrators' == Workflow administrators?

![image](https://user-images.githubusercontent.com/17581159/92822158-3343f580-f40f-11ea-95b1-31cecbb8e0aa.png)

Your questions:

* User reports doing "nothing differently" when I asked if they experienced a slow page, or if they clicked Approve multiple times, or if they received multiple emails to approve. The user is not new to this approval system so I'm hopeful that they're relaying good info here, i.e. they did indeed only click Approve at Stage 2. The timestamps associated with the progression between stages seems to be a few seconds, so it doesn't seem like it was an automated progression (i.e. would expect it all in the same second) but I don't know exactly what "workflow completing automatically" means exactly, outside of what Implicit Approval does.

* User does not have access to the workflow section in backoffice, i.e. I asked them to visit https://snip/umbraco/#/workflow/workflow/settings/info and report what they saw, and it was the Umbraco dashboard and not the Workflow settings page (i.e. where 'lock active content' is available for setting). Hope I have understood that correctly.

Thanks again.

**Comment by nathanwoulfe** [comment]
That's definitely a bit odd - like you said, the timestamps don't suggest that the workflow skipped steps, there's several seconds between stages being completed. If the user doesn't have access to the workflow section, they should not be able to approve as admin, because they're not admin...

Wondering if it's a SignalR issue, and UI isn't updating when the task is completed, although that wouldn't explain why there's time between each stage, unless the user is clicking multiple times. Sometimes I've seen the SignalR hub disconnect when it shouldn't...

I'll spin up a test scenario on the latest codebase and see if I can replicate. Would be good to know too if there are any JS errors logged, but without your user replicating the issue, that's pretty difficult to ascertain.

**Comment by nathanwoulfe** [comment]
Right. I've run through the following:
- configured a workflow with five steps, different group for each step
- added a user to the second step group, and only that group
- user is not admin
- started workflow
- user approved
- user could not take any further action

The user had no option to approve the content in subsequent steps, either via the dashboard or the node. However, there was a slight delay (~1 second, probably not even that long) for the footer button to update from `approve workflow` to `workflow detail` after approving, so there's potentially an opportunity for the user to click that button and open the approval overlay, which does allow them to submit again, and shows them as completing as admin. I think that's what's happened here.

I'll have a look at better managing how the button state updates, and improving the check on the user when actioning the task. Definitely looks like your user has approved the task multiple times by clicking again while the task is being processed, that's the only way I can replicate the issue.

**Comment by tkf144** [comment]
Thanks @nathanwoulfe. Your ~1 second delay would be reasonable to extend to a few seconds, based on the overall speed of our Umbraco instance (I assume ours is slower than normal due to the incredible perf discrepancy between the fresh, local Umbraco install I had once, before I loaded our content/media in). So it seems very reasonable that the 3-5 second gaps between the stage progression would line up with what you describe above.

I will get marketing to attempt to repro based on your response and let you know if we see the same thing.

**Comment by nathanwoulfe** [comment]
@tkf144, I did a bit more digging, and hopefully have found the fix - there's a pair of events raised when a workflow task is submitted, one to modify the state of the footer button (changing it from busy back to active) and one when the task is completed, to trigger an update to the button action. By swapping the order that these are emitted, I think it should resolve the issue, because the button will be in the busy state until it has updated, so can't be clicked until it is bound to the correct handler:

- task is submitted
- button is busy
- task submission completes
- button handler is updated
- button is not busy

Prior to these changes, it worked like this:

- task is submitted
- button is busy
- task submission completes
- button is not busy
- button handler is updated

which left the period between the last two steps as the potential window for approving the next task. 

In my (admittedly quick) tests, it seems to have resolved the issue, there's no display of the previous button after submitting a task, button progresses from busy to the correct state. There's a CI build available now at https://ci.appveyor.com/project/nathanwoulfe/umbracoworkflow/build/artifacts if you want to try dropping the updated javascript into a test site to verify

**Comment by tkf144** [comment]
Have spent the afternoon trying to repro in the manner you describe above @nathanwoulfe, but have had no luck. Did spot the "Approve" button re-appearing after an approval for a *very* brief moment, but on clicking it, the Workflow Detail pane appeared and did not present any option to approve again. This was focusing on repro via the footer buttons when editing the content/node.

Ironically, despite my "Do not action!" change description, Blue User approved my test change at the same time as one of my test users, and of course.. a successful repro.

<img src="https://user-images.githubusercontent.com/17581159/93054738-280df580-f6ad-11ea-8f61-04c4e6c0608f.png" width="50%" />

```
2020-09-14 16:26:11,040 [82] INFO  Workflow.Api.ActionsController - Workflow Publish task on CONTENT TITLE [16445] approved by TF2 
2020-09-14 16:26:13,834 [36] INFO  Workflow.Api.ActionsController - Workflow Publish task on CONTENT TITLE [16445] approved by BLUE USER 
```
(note ~2s between)

This set me thinking that maybe it was the concurrent-ish approval that triggers the issue, so I set up another workflow instance and scripted 2 test users to approve at the exact same time via devtools.

```js
// Inspect the submit <Button />
let elementToClick = $0; setTimeout(function() {
    elementToClick.click()
}, Date.parse("2020-09-14T16:57:00") - Date.now());
```

This did not repro, but instead created two of the next stage:

<img src="https://user-images.githubusercontent.com/17581159/93055139-cdc16480-f6ad-11ea-8e7b-e2d5b7ecfd0b.png" width="50%" />
<img src="https://user-images.githubusercontent.com/17581159/93055171-da45bd00-f6ad-11ea-956c-c549dfbe6748.png" width="50%" />

I switched to trying to repro via the *Tasks requiring my approval* dashboard and had more luck after I added a 0.5s delay to the auto-submit for 1 of the 2 users approving simultaneously and that seems to have reproduced the issue:

```js
let elementToClick = $0; setTimeout(function() {
    elementToClick.click()
}, Date.parse("2020-09-14T17:49:00") - Date.now() + 500);
```

After submission, the approval item row on the dashboard does not appear to clear, and allows approval again.

(TF2 and TF3 were set to simultaneously approve Stage 2. Both their approvals succeeded in terms of UI feedback, but TF3s 'won'. TF2's row on the dashboard remained allowing approval at Stage 3)
<img src="https://user-images.githubusercontent.com/17581159/93059310-de74d900-f6b3-11ea-903d-84709464dfea.png" width="50%" />
<img src="https://user-images.githubusercontent.com/17581159/93060564-ac647680-f6b5-11ea-960c-4e308830adc0.png" width="50%" />

Hope this helps.
