### ISSUE TITLE
WorkflowInstalled appSetting Key Infinate Loop On Umbraco Cloud

### ISSUE THREAD

**Issue by fnkymnky** [nathanwoulfe/Plumber#74]
**Describe the bug**
We installed the Plumber extension on our Umbraco Cloud environments (Dev, Staging and Live) and set up groups, added nodes to workflow, etc. 

After performing a server restart a couple of days later, we found our Dev environment became unresponsive, stuck in a page loading state.

We raised the issue with Umbraco Cloud support and they said the following:

> The customer installed a package called Plumber, which keeps bumping the web.config resulting in a restart constantly.
> Looking at the web.config there is an appSetting key called WorkflowInstalled which is constantly getting longer.
> <add key="WorkflowInstalled" value="True,True,True,True,True,True,True,True,True,True,True,True,True
(it just continues)
> The issue would be resolved by removing the package. 

Further to this, they also said:
> We don't have a real answer to what started it, but we think that it is the .uda file change. Since Plumber is a third party workflow tool it seems likely that it would listen for such an event, but we have no way to know how it's put together. We'd recommend you to reach out to Nathan Woulfe, the creator of the package. 

The Dev server is stuck in a restart loop and doesn't end without removing the package. We had this same issue in the past and had to remove it. After re-installing it a few months later, all seemed to be fine and no restart loop.

There are a few errors in the Cloud error log, but they all relate to resources being deadlocked and not being able to access them (presumably due to the restart loop?).

There is, however, one error I think could be of help:
```
Message:
An error occurred running OnApplicationStarted for handler Workflow.Startup.UmbracoStartup
								
Exception:
System.Configuration.ConfigurationErrorsException: An error occurred loading a configuration file: The process cannot access the file 'C:\inetpub\temp\DWASFiles\Sites\8861958a-aecb-4aa0-a261-e81ee5d83884\VirtualDirectory0\site\wwwroot\web.config' because it is being used by another process. (C:\inetpub\temp\DWASFiles\Sites\8861958a-aecb-4aa0-a261-e81ee5d83884\VirtualDirectory0\site\wwwroot\web.config) ---> System.IO.IOException: The process cannot access the file 'C:\inetpub\temp\DWASFiles\Sites\8861958a-aecb-4aa0-a261-e81ee5d83884\VirtualDirectory0\site\wwwroot\web.config' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at System.Configuration.Internal.InternalConfigHost.StaticOpenStreamForRead(String streamName)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.OpenStreamForRead(String streamName, Boolean assertPermissions)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigHost.OpenStreamForRead(String streamName)
   at System.Configuration.Internal.DelegatingConfigHost.OpenStreamForRead(String streamName)
   at System.Configuration.UpdateConfigHost.OpenStreamForRead(String streamName)
   at System.Configuration.BaseConfigurationRecord.InitConfigFromFile()
   --- End of inner exception stack trace ---
   at System.Configuration.ConfigurationSchemaErrors.ThrowIfErrors(Boolean ignoreLocal)
   at System.Configuration.BaseConfigurationRecord.ThrowIfParseErrors(ConfigurationSchemaErrors schemaErrors)
   at System.Configuration.Configuration..ctor(String locationSubPath, Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Configuration.Internal.InternalConfigConfigurationFactory.System.Configuration.Internal.IInternalConfigConfigurationFactory.Create(Type typeConfigHost, Object[] hostInitConfigurationParams)
   at System.Web.Configuration.WebConfigurationHost.OpenConfiguration(WebLevel webLevel, ConfigurationFileMap fileMap, VirtualPath path, String site, String locationSubPath, String server, String userName, String password, IntPtr tokenHandle)
   at Workflow.Startup.UmbracoStartup.ApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext context)
   at Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   at Umbraco.Core.CoreBootManager.<Complete>b__38_0(IApplicationEventHandler x)
```

**To Reproduce**
I'm unsure of exactly how to reproduce the issue, as it only seems to occur on our Development environment. The code base for all environments is the same and we have the same content syncd.

**Comment by nathanwoulfe** [comment]
The write to web.config is used as a flag to avoid the installer running on restarts - it shouldn't be written to again if the flag exists. 

I'll change that to check instead if the Plumber application exists, avoiding the file writing altogether.

**Comment by nathanwoulfe** [comment]
Just had a poke around, there's nothing in the installer that should be causing the loop - it's a simple check for a key in appsettings, then if that exists checking that it is equal to true.ToString() (which it must be, since it's only ever set to true.ToString())

Wondering if there's something Cloud-specific that would be causing this? Is the dev web.config pulled from a different environment or anything like that? Again though, can't see why that would cause a loop  - the setting key is either present or not, and is only set after the install runs,, when the key didn't exist...

**Comment by nathanwoulfe** [comment]
It's strange. The user config won't cause it, since the writing only happens on app startup, and only when the key doesn't exist. I'll get a build out sometime today, which should resolve hopefully resolve it...

**Comment by nathanwoulfe** [comment]
I'm building a version now where the installed doesn't check the value of the worfklowInstalled app setting, just that it exists. I think what has happened is that at some point, for whatever reason, the value in the key changed from `True`, which cause the startup handler to run the installer and update the key - that then means the key value would become `oldValue,True`, in turn causing an app restart, installer runs because the key value isn't `true.ToString()`, key value updates to `oldValue,True,True` and the loop continues.

Hopefully by simply checking for the key presence, the installer runs once on initial startup, creates the key with `true.ToString()` and never gets called again since I no longer care what the value is, just that something exists...

Build is available from https://ci.appveyor.com/project/nathanwoulfe/umbracoworkflow/build/artifacts, just need the DLL from the zip. Dump that in /bin, and should be ok, regardless of the value in the web.config...

Let me know how you go, if this works I'll push out a patch release.

N

**Comment by mderriey** [comment]
> We've had to remove the extension from our dev environment in order to get access again, which means removing it from our other cloud environments to avoid code conflicts.

One thing we found that helped is remove the `WorkflowInstalled` key from the `web.config`. That triggers an application restart and stops the continuous restarts. Don't know if you have access to the file directly with Umbraco Cloud.

/cc @fnkymnky

**Comment by nathanwoulfe** [comment]
Got me stumped - the code writing to the web config is pretty straightforward, can't see anything there which is an obvious cause...

Let me know if the patch works and I'll push out a release.

**Comment by nathanwoulfe** [comment]
@mderriey @fnkymnky - have either of you been able to verify the patch resolves this issue? I'd like to release it if so.

ta
N

**Comment by mderriey** [comment]
@nathanwoulfe I was trying to get a consistent set of steps/situations to repro and it hasn't happened in a while, so unfortunately I'm afraid applying the patch won't allow us to confirm anything.

**Comment by nathanwoulfe** [comment]
v1.0,1 has this change, please let me know if it resolves the issue.

**Comment by fnkymnky** [comment]
Just getting round to trying this out today!

Correct me if I'm doing something stupid, but I downloaded the .zip of the latest release (linked above) and added the .dll file (9753aea8-7d92-4a9b-8e1d-9d480a391e92.dll) to my local bin folder and got the following error in event log, after getting an Error 500 when loading the site:

> Could not load file or assembly '9753aea8-7d92-4a9b-8e1d-9d480a391e92' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at System.Web.Configuration.CompilationSection.LoadAssemblyHelper(String assemblyName, Boolean starDirective)

What am I missing? Should I just install the full alpha package instead?

**Comment by nathanwoulfe** [comment]
Renaming it makes sense - the zip has everything renamed for the Umbraco package installer to work its magic.  If that doesn't resolve it, I'm at a loss as to what could be causing it - setting a value in the web config is pretty standard, so it shouldn't be tripping up Cloud...

**Comment by fnkymnky** [comment]
So I've done the following steps:

- Renamed the dll from your patch to Workflow.dll and added it to my v1.0.1 package install (overwriting the existing .dll)
- Uploaded that to my dev environment
- Tried a variety of tests, including restarting the environment a number of times, submitting items for approval and publishing, etc

Pleased to say that it all looks stable good so far!

I've now deployed the changes to my staging environment and will monitor it for the next couple of days. I'll let you know if there are any further issues.

Thanks Nathan!
